/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Locale;
import javax.swing.JOptionPane;
import restuarantautomationsystem.Controller;

/**
 *
 * @author karpagaganeshpatchirajan
 */
public class EmployeeLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeLoginGUI
     */
    public EmployeeLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        loginGUIOkButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Restuarant Automation System");

        jLabel2.setText("Employee ID");

        jLabel3.setText("Password");

        empText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTextActionPerformed(evt);
            }
        });

        loginGUIOkButton.setText("Ok");
        loginGUIOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginGUIOkButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(258, 258, 258)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(94, 94, 94)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel3))
                        .add(73, 73, 73)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(empText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .add(passwordText))))
                .addContainerGap(233, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(loginGUIOkButton)
                .add(29, 29, 29)
                .add(jButton2)
                .add(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(72, 72, 72)
                .add(jLabel1)
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(empText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(passwordText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(40, 40, 40)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loginGUIOkButton)
                    .add(jButton2))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginGUIOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginGUIOkButtonActionPerformed
        // TODO add your handling code here:
        
        boolean status = false;
        String empID = null;
        String password = null;
        while(status == false){
            empID = empText.getText();
            password = passwordText.getText();
            if(!empID.isEmpty() && !password.isEmpty() ){
                Controller controller = new Controller();
                status = controller.EnterCredentials(empID,password);
                if(status = true){
                    WaiterGUI waitergui = new WaiterGUI();
                    waitergui.showGUI();
                }
            }
            else if(empID.isEmpty() && password.isEmpty()){
                
                JOptionPane.showMessageDialog(null, "Emp ID & Password is mandatory");
                    break;
            }
            else if(empID.isEmpty()){
                JOptionPane.showMessageDialog(null, "Emp ID is mandatory");
                passwordText.setText(null);
                    break;
            }
            else if(password.isEmpty()){
                JOptionPane.showMessageDialog(null, "Password is mandatory");
                    break;
            }
            
        }
    }//GEN-LAST:event_loginGUIOkButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        empText.setText(null);
        passwordText.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void empTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTextActionPerformed

    /**
     * User Defined Methods
     */
    
    public void showGUI(){
        setVisible(true);
        empText.setText("test");
        passwordText.setText("test");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLoginGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginGUIOkButton;
    private javax.swing.JTextField passwordText;
    // End of variables declaration//GEN-END:variables

    void hideGUI() {
       this.dispose();
    }
}
